### ISSUE TITLE
"@Nami-Doc how do i use commonjs-everywhere with 3rd party components? seems like component(1) is a better builder"

### ISSUE THREAD

**Issue by vendethiel** [aeosynth/iv#1]
qqueue/html5chan@ab815341354ac2be1901dea2e611301a8ee341ed

**Comment by aeosynth** [comment]
ok, so you're using `npm` as the package manager, and `commonjs-everywhere` looks through `node_modules`

**Comment by vendethiel** [comment]
Ye basically but since I have my stuff in `src/` soo I have to `require '../rootmodule'` which is really crappy. I think brunch + components is  better bet (even if most components  are npm-registered)

**Comment by vendethiel** [comment]
Nami-Doc/wowboardhelpers@3b339d83be Nami-Doc/wowboardhelpers@16cfdc0ca7
